all_tweets = []
all_tweets.append((False, 'Apple', 'I mean $2 million for every car the company $862m #startup #tech'))
all_tweets.append((False, 'Apple', 'The update going through Apple pay verification into the apple sauce Dave'))
all_tweets.append((False, 'Apple', "I love apple season and we've got a free app today >;>; #Arianators"))
all_tweets.append((False, 'Apple', 'I love apple cider and. 4G Ram'))
all_tweets.append((False, 'Apple', 'Apple crumble they made it in the app for the apple sauce, though run out'))
all_tweets.append((False, 'Apple', 'I just got easier. The old MSD'))
all_tweets.append((False, 'Apple', 'Apple bottom jeans is on iTunes.. Via @thenextwe'))
all_tweets.append((False, 'Apple', 'The farthest I can just pay through apple pay verification into the Halloween'))
all_tweets.append((False, 'Apple', 'I wanna wake up to fresh bread, scones, cookies, apple juice #thestruggleisreal'))
all_tweets.append((False, 'Apple', 'I wanna wake up album is doing reminds me of a chase. He was getting an error charging my Apple face masks again before my face.. #ASMSG'))
all_tweets.append((False, 'coding', 'Coding my tweets. I prefer coding long hours of intense coding, programming, 3D'))
all_tweets.append((False, 'coding', 'I know how much fun I admit just wish I could finish my coding skills required'))
all_tweets.append((False, 'coding', "The repetitiveness of finance? I'm against too"))
all_tweets.append((False, 'coding', 'How do you have enough with this assembly themed around coding'))
all_tweets.append((False, 'coding', 'Coding my fic page, in theory ;'))
all_tweets.append((False, 'coding', "The repetitiveness of finance? I'm impressed. So cute. Is going VERY"))
all_tweets.append((False, 'coding', "I honestly can't wait until this weekend, still working on Illustrator"))
all_tweets.append((False, 'coding', "I honestly can't wait to get rid of it is.. I have a coding competition _ _"))
all_tweets.append((False, 'coding', 'How to code for the Big win here, hard copies there. Woooooh! #collegelife'))
all_tweets.append((False, 'coding', 'The problem. Hour long coding? The simplicity of life on the outside coding phenomenon: XybFtS'))
all_tweets.append((False, 'dude', 'Dude I have to get up to my man LAWD'))
all_tweets.append((False, 'dude', 'I mean tru but dude come out here getting pounced for dude cuz me and u know its very important!'))
all_tweets.append((False, 'dude', 'Happy mask tylor is so hard to keep listening. I usually get the kids to school. Lol lol'))
all_tweets.append((False, 'dude', 'Happy Birthday, dude? You make it! Her live-in boyfriend.. Dude I need the illest barber in deltona'))
all_tweets.append((False, 'dude', 'Dude I need it! Eat disgusting aubergine, that Syarif'))
all_tweets.append((False, 'dude', "I know this whole situation is annoying the kids he already has, wtf? That's scary!"))
all_tweets.append((False, 'dude', 'I dont even know what you hear about enlistment in this Screening'))
all_tweets.append((False, 'dude', 'Happy bday an awesome game aw and thinking is there dude. How does that dude was cool naw lil guy'))
all_tweets.append((False, 'dude', "Dude I need it dude, I'm so done with Twitter"))
all_tweets.append((False, 'dude', 'Dude. You never at school dude holy fuckkk'))
all_tweets.append((False, 'halloween', 'The greatest gift u can be Bane'))
all_tweets.append((False, 'halloween', 'Halloween party! These simple tips to ensure that your.. Halloween decor.. -'))
all_tweets.append((False, 'halloween', 'The halloween candy. Feed the kids'))
all_tweets.append((False, 'halloween', "This halloween or you'll be getting tricks Cuz"))
all_tweets.append((False, 'halloween', 'Halloween is fast approaching so get your spooky pics Perkers'))
all_tweets.append((False, 'halloween', 'The nightmare on _____ street for Halloween and wearing this'))
all_tweets.append((False, 'halloween', 'The signs as Halloween icon I havent even finished moms bday present'))
all_tweets.append((False, 'halloween', 'Halloween movies w/ me and go for the Halloween spirit by making niall his costume'))
all_tweets.append((False, 'halloween', "I still don't know if i'l finish it in your diary! Join #godsgirls for 50% off Halloween but it's so hard to believe, but it's so close I"))
all_tweets.append((False, 'halloween', 'This was a three day weekend and halloween with my little niece and nephew #pumpkin #halloween'))
all_tweets.append((False, 'happy', 'I want matt to wish u many yrs in return. I wish that for a moment and make you so so cute and make you happy?  Uncommon'))
all_tweets.append((False, 'happy', 'HAPPY birthday bro x @TyrellColey13'))
all_tweets.append((False, 'happy', 'Happy happy. Would you on air tho*'))
all_tweets.append((False, 'happy', 'HAPPY birthday bro x @TyrellColey13'))
all_tweets.append((False, 'happy', 'I hope he feels loved and for having self confidence and being one of a man He'))
all_tweets.append((False, 'happy', 'HAPPY to help out - will pass it on Let'))
all_tweets.append((False, 'happy', 'HAPPY bday? Happy?  By on #SoundCloud'))
all_tweets.append((False, 'happy', 'Happy bday beautiful. It makes you #happy..! Stay the same birthday! Have fun be'))
all_tweets.append((False, 'happy', 'HAPPY happy!! Happy tuesday.'))
all_tweets.append((False, 'happy', 'Happy navratri maa durga bless u all Happy Tuesday.'))
all_tweets.append((False, 'hockey', "I want tabinof now but it's best to our U10"))
all_tweets.append((False, 'hockey', 'The dogs on swings is what makes hockey look sooo easy. See? This twitter used to lose 50 pounds #TFB'))
all_tweets.append((False, 'hockey', 'I want also inv few players from up north coming down for ncaa hockey voice; great kid on Super'))
all_tweets.append((False, 'hockey', 'Hockey naps they call them over and under!'))
all_tweets.append((False, 'hockey', "I just saw this on the road hockey against someone online and losing. Let's chill tonight and support the girls won 4-0 against Wellington"))
all_tweets.append((False, 'hockey', "Hockey isn't about losing a hockey team is winning the Test match? Missing Hall"))
all_tweets.append((False, 'hockey', 'I just find it with this dirty shootout move from last week/no ban and rightly so'))
all_tweets.append((False, 'hockey', 'Hockey is for sale.. #NHL #a'))
all_tweets.append((False, 'hockey', 'Hockey is my life @Cacey_Bertram'))
all_tweets.append((False, 'hockey', 'Hockey naps they call them over and under!'))
all_tweets.append((False, 'news', 'How we will know the local community, send your #international news press releases to news@philanthropyjournal. Org'))
all_tweets.append((False, 'news', 'The modus operandi is to keep away from boko haram but they were held captive in labs! #dogs #cats'))
all_tweets.append((False, 'news', 'The modus operandi is to be recorded separately for first line responders: 1 . 4 sq kms of land in North'))
all_tweets.append((False, 'news', 'How we break it. In what appears to show up for sale - sources'))
all_tweets.append((False, 'news', 'How we will know the difference. #RWC2015'))
all_tweets.append((False, 'news', 'The #business #consulting news is saying we will know the EU'))
all_tweets.append((False, 'news', 'The #business #consulting news is saying we will go on.. #news #finance'))
all_tweets.append((False, 'news', 'A good time to be an brilliant engineer. #ILookLikeAnEngineer'))
all_tweets.append((False, 'news', "A good sulking day. Talking abt law did u coverage poojary's news until now has been showing the probable path o . . #news #culture #life"))
all_tweets.append((False, 'news', 'The #business #consulting news is different hair. Shock fans. #Samba'))
all_tweets.append((False, 'obama', 'President Obama please do everything short of appalling. Red light to turn it into.. - By JDB'))
all_tweets.append((False, 'obama', 'I wanna see this victims father.. Related to President'))
all_tweets.append((False, 'obama', 'President Obama found some sort of amazing'))
all_tweets.append((False, 'obama', 'I wanna see this country than any time and for obama is a traitor of course! : NGA'))
all_tweets.append((False, 'obama', 'Obama "legacy" has MORE similarities to Obama'))
all_tweets.append((False, 'obama', 'The obama regime/supporters the rest... - Bearing'))
all_tweets.append((False, 'obama', 'President obama found some sort of #Syria'))
all_tweets.append((False, 'obama', 'Obama has gotten rid of ISIS. Obama?'))
all_tweets.append((False, 'obama', 'Obama has 0 say in the world is better than Trump'))
all_tweets.append((False, 'obama', 'President obama very scary.. Related to President'))
all_tweets.append((False, 'random', "I was kuroo and I don't add guys on my phone in my room.. #random #90stweet"))
all_tweets.append((False, 'random', 'Random but I actually think that guy is all. And if you do?'))
all_tweets.append((False, 'random', 'When the video came out of a girlfriend?  While his girlfriend w'))
all_tweets.append((False, 'random', 'Random question. I love hotel transylvannia'))
all_tweets.append((False, 'random', 'Random people in New spending, 3 Edmund'))
all_tweets.append((False, 'random', 'I just read some random girl I met you'))
all_tweets.append((False, 'random', 'When u think u see throughout ur day to day. I luh history.'))
all_tweets.append((False, 'random', 'I think about.  See more #bigtits at #NSFW'))
all_tweets.append((False, 'random', 'I was leaving for the best in Thurrock'))
all_tweets.append((False, 'random', 'When the girl with curly blonde hair huehue'))
all_tweets.append((False, 'weird', "I think it's weird. Like I stole something"))
all_tweets.append((False, 'weird', 'Weird, like, 1000 miles?? Weird? I see te word Folk'))
all_tweets.append((False, 'weird', "Weird how much I can see why like something is behind you I'm"))
all_tweets.append((False, 'weird', 'Weird how you feel good, but that shit is when your weird cousins on Facebook?? I see te word Folk'))
all_tweets.append((False, 'weird', "I feel weird about it! I mean if u dye ur hair ur style u and stiga to claim a freebie!! So weird and it's kinda itchy."))
all_tweets.append((False, 'weird', 'I feel connected with them anywhere else, but that would qualify.'))
all_tweets.append((False, 'weird', 'Weird, and the next u feel so inspired to do that though'))
all_tweets.append((False, 'weird', 'I have weird dreams that involve people that work there. Me too, Haste'))
all_tweets.append((False, 'weird', 'I think about what fictional characters would be good or bad?'))
all_tweets.append((False, 'weird', 'I think that I only like Mista'))
all_tweets.append((True, 'Apple', "Baby, we're the New Romantics. #TS1989 #taylurking"))
all_tweets.append((True, 'Apple', '#Tech #GoldCoast Apple announces new 4K and 5K iMacs with Australia pricing'))
all_tweets.append((True, 'Apple', 'The girls in the Apple Music Festival'))
all_tweets.append((True, 'Apple', 'luxury technology A French Luxury Brand Builds an Apple Watch Rival'))
all_tweets.append((True, 'Apple', 'iCreative_Brand: limey59music: "552010" - EP by Leona\\\'s Sister #iTunes #IndieMusic #TuesdayTunes #Canada #Toron'))
all_tweets.append((True, 'Apple', 'I liked a video If McDonalds Advertised Like Apple'))
all_tweets.append((True, 'Apple', "Lightning strikes again for Apple, as new accessories go their own way: Apple's newest Mac accessories use the..."))
all_tweets.append((True, 'Apple', 'Inside the lab: Why Apple still sweats the details on iMac'))
all_tweets.append((True, 'Apple', 'Time to merge iOS and OS X?'))
all_tweets.append((True, 'Apple', 'Apple updates iMacs with 4K and 5K Retina displays: Apple has updated its iMac range with Retina 4K and 5K displays, and Force Touch ...'))
all_tweets.append((True, 'coding', "Highlighting features but not colouring coding so it doesn't make sense so you can't do your essay that's due on Friday #sixthformproblems"))
all_tweets.append((True, 'coding', 'Morrisons Milk for Farmers hits the shelves via @FoodManufacture'))
all_tweets.append((True, 'coding', 'Checkout by Octobat: No coding, no struggling with taxes, just a better payment experience via cc @Daiquiri'))
all_tweets.append((True, 'coding', 'Couples coding sesh with @oliviayonk.'))
all_tweets.append((True, 'coding', 'There is a lot of power in seeing someone who might be future you.'))
all_tweets.append((True, 'coding', 'SUPER VAG K + CAN V4.8.1 VW AUDI SEAT SKODA SCANNER KEY CODING SCAN TOOL BEST'))
all_tweets.append((True, 'coding', "Took a caffeine tablet. It's coding time."))
all_tweets.append((True, 'coding', 'Learn how to make iPhone apps in 1 hour without any coding #iPhone'))
all_tweets.append((True, 'coding', 'Coding error'))
all_tweets.append((True, 'coding', 'Who likes OCs and likes coding games cause I have my webcomic that needs more OCs, and I were prefer it to be a game-'))
all_tweets.append((True, 'dude', 'Stan: Dude, dolphins are intelligent and friendly. Cartman: Intelligent and friendly on rye bread with some mayonnaise.'))
all_tweets.append((True, 'dude', 'gotta get one with Prime Himself dude'))
all_tweets.append((True, 'dude', "Shit .. I'm probably the healthiest dude yah know at 20"))
all_tweets.append((True, 'dude', 'Laundry Woes / Silver Dude - Regular... | #tv #episode #Laundry #Woes #/ #Silver #Dude ...'))
all_tweets.append((True, 'dude', '. mansplains directly to @benshapiro. She really is a dude.'))
all_tweets.append((True, 'dude', 'dude I got some lyrics if you wanna buy them from me'))
all_tweets.append((True, 'dude', 'oHh coME ON DUDE HOW CAN YOU CHOOSE JUNHOE THAN YOUR BANDMATES'))
all_tweets.append((True, 'dude', "that's ducking awesome dude. congrats to her"))
all_tweets.append((True, 'dude', "Dude omg that's my most hated line ever lol like agh I straight up just say I am a guy like me hahahah"))
all_tweets.append((True, 'dude', 'Why does it feel like a fucking Monday dude'))
all_tweets.append((True, 'halloween', "It's the perfect time of year for me to get into this show. #ahs #ahshotel #tv #october #Halloween"))
all_tweets.append((True, 'halloween', 'Trying to find places to stick magic poster up.. Woo. Thanks to'))
all_tweets.append((True, 'halloween', "So far I've got two Halloween costumes and I need one more. Give me your worst suggestions."))
all_tweets.append((True, 'halloween', 'i already prepare things for halloween'))
all_tweets.append((True, 'halloween', 'Halloween Stream Announcement: Clock Tower 2: The Struggle Within on 10/30! Starts 9PM EST!'))
all_tweets.append((True, 'halloween', 'Theo Moudakis: Harper bans Halloween'))
all_tweets.append((True, 'halloween', 'Read #Arthurian #ScienceFantasy at #Halloween for spooky scare Shadow Over Avalon #99c #ASMSG'))
all_tweets.append((True, 'halloween', 'Happy Halloween! #HauntedHouse I created on @realtordotcom. #sharethescare #Halloween'))
all_tweets.append((True, 'halloween', "what's Logan gonna be for Halloween?"))
all_tweets.append((True, 'halloween', 'my aunt: happy birthday (a bunch of halloween and christmas emoticons)'))
all_tweets.append((True, 'happy', "the evil ones who don't like to see anyone happy are waiting in the shadows to take shots at the no bra pics"))
all_tweets.append((True, 'happy', 'ALWAYS be Honest, ALWAYS be considerate, ALWAYS be respectful. Happy Tuesday!!!! #feleciaisawinner'))
all_tweets.append((True, 'happy', 'you changed my life. thank you for everything you do, I hope you are happy and well, please follow me? 18,519'))
all_tweets.append((True, 'happy', 'I remixed a true classic! It is one of the big tracks in my sets this year and I`m happy to announce that it will...'))
all_tweets.append((True, 'happy', 'Happy Birthday !.. Enjoy your Day!'))
all_tweets.append((True, 'happy', 'Happy birthday to my FAVEorite gwal you are one of a kind'))
all_tweets.append((True, 'happy', 'Happy Tuesday friends.. Wish everyone a Productive Week #AlwaysOnAMove #Respect Humbled #Scurr..'))
all_tweets.append((True, 'happy', 'Happy birthday to the goat himself'))
all_tweets.append((True, 'happy', 'Happy to see them together to watch #ASOP4GrandFinals A Song of Praise'))
all_tweets.append((True, 'happy', '#Repost longhornsx with repostapp. Happy birthday Real G! Bless Up'))
all_tweets.append((True, 'hockey', 'Rookie Eichels splendid goal sparks Sabres #japan'))
all_tweets.append((True, 'hockey', 'Seattle Thunderbirds WHL Vintage 11" x 14" 3rd/Alt. Hockey Jersey Crest Patch - Bid Now! O'))
all_tweets.append((True, 'hockey', 'ICYMI: on The National.'))
all_tweets.append((True, 'hockey', 'Or ever, in hockey at least.'))
all_tweets.append((True, 'hockey', '#watch #live Jokerit vs Metallurg Magnitogorsk #hockey stream online .'))
all_tweets.append((True, 'hockey', "no I haven't yet. I'm not in hockey mode yet. I'm far from a fair weather #Leafs fan but I don't have the energy to invest right now"))
all_tweets.append((True, 'hockey', '#eBay Vtg #NHL Hockey Retro 80s Montreal Canadiens Sewn Jersey Men S Red #OpenFollow'))
all_tweets.append((True, 'hockey', '#Best New York Rangers CCM Hockey Jersey Statue Of Liberty #NHL White Size Medium #TFBJP'))
all_tweets.append((True, 'hockey', 'Gotta love opening season tournament - 50 Shades of Grey team in action.'))
all_tweets.append((True, 'hockey', '#Edmonton Edmonton #Oilers Reebok NHL Team Colors Knit Beanie W/ Pom Hat Cap #NHL #Hockey'))
all_tweets.append((True, 'news', 'Compton rapper films selfie video after being shot in the head by a hail of stray bullets'))
all_tweets.append((True, 'news', "This gene might be why elephants don't get cancer."))
all_tweets.append((True, 'news', 'Man Utd, Liverpool in for Jorginho? #FootballNews'))
all_tweets.append((True, 'news', "Twitter Not Happy With Ellen DeGeneres' Nicki Minaj Parody"))
all_tweets.append((True, 'news', "First female bishop to take Lord's seat"))
all_tweets.append((True, 'news', 'Video: BRITNY FOX Performs ANGEL Classic With FRANK DIMINO'))
all_tweets.append((True, 'news', "Ankara attacks intensify Kurdish party's conflict with Erdogan #Politics"))
all_tweets.append((True, 'news', 'Klopp greets Liverpool supporters after training: New Reds boss stops for pictures and autographs with ... #lfc'))
all_tweets.append((True, 'news', 'Tom Brady not concerned with revenge vs. Colts: Tom Brady and the New England Patriots face the Indianapolis Cols'))
all_tweets.append((True, 'news', 'College #niggger football player accused of stabbing teammate with corkscrew via @MailOnline'))
all_tweets.append((True, 'obama', 'Somebody needs to throw a bucket of cold water on President Obama and his "lead from behind" cohort of foreign...'))
all_tweets.append((True, 'obama', 'when Obama go accept Mugabe in proposal......we dey wait ooo'))
all_tweets.append((True, 'obama', "If Obama really wanted to do something about gun violence, he'd go after criminals, not l"))
all_tweets.append((True, 'obama', 'Obama Tells 60 Minutes Hillary Clinton Made Email Mistake, via'))
all_tweets.append((True, 'obama', 'Syria\\\'s Al-Nusra calls on jihadists in Caucasus to attack Russia >;Obama\\\'s "Good Terrorists" with the same hot air..'))
all_tweets.append((True, 'obama', 'c5wired97: CarmineZozzora: Obama: My definition of leadership would be leading on climate change... #WakeUpAme'))
all_tweets.append((True, 'obama', "Typical #Obama can't wait to arm #criminals radicals. #Muslims #IranDeal #ISIS #WakeUpAmerica"))
all_tweets.append((True, 'obama', '-Sean- come out of your bubble- The American People does not recognize Obama as Our President-'))
all_tweets.append((True, 'obama', "Don't forget Obama said he would never retaliate against a nuke attack with nukes."))
all_tweets.append((True, 'obama', 'Drug inmates with long rap sheets among those freed early The true Obama is showing, thanks use'))
all_tweets.append((True, 'random', "You demand far too much trust, random mouthwash dispenser in a Men's bathroom."))
all_tweets.append((True, 'random', '[ENG} Playing some random games:'))
all_tweets.append((True, 'random', 'Deputies say they do not believe this was a random shooting.'))
all_tweets.append((True, 'random', 'Waking up to a random dick pic from my ex is not how I planned starting my day'))
all_tweets.append((True, 'random', "Billy On The Street Talks Pizza Rat Being Gay, Donald Trump's Anus-Mouth, And Other Hilar... #random"))
all_tweets.append((True, 'random', 'my life is so random'))
all_tweets.append((True, 'random', 'I think it better to do random checks of weakening poles before the worst comes'))
all_tweets.append((True, 'random', 'Random lyrics locks! - retweet first mbf us tweet us which one'))
all_tweets.append((True, 'random', 'Remember when SJ tried to play random dance and Kyuhyun was in a "fall mood":'))
all_tweets.append((True, 'random', 'random viber photo msg haaaaay,thank you'))
all_tweets.append((True, 'weird', 'Listening to the Spurrier press conference.. Gonna be weird to not have the HBC on the sidelines during College...'))
all_tweets.append((True, 'weird', "Abbie is making sex noises with her own tit and it's really weird"))
all_tweets.append((True, 'weird', 'He are so weird and idiot but I love him'))
all_tweets.append((True, 'weird', 'People with small ears look weird'))
all_tweets.append((True, 'weird', "Omg am I really that talkative that when I don't talk, it's very weird? hahaha!"))
all_tweets.append((True, 'weird', 'right now? Egypt.'))
all_tweets.append((True, 'weird', 'Youre_Glowing "First viewings on our little house tonight - eeek! Feels weird to think of strangers inspecting our'))
all_tweets.append((True, 'weird', 'I had a weird dream that @theotherJoeCole, Me went 10 pin bowling as Peaky Blinders. If ever there were life goals...'))
all_tweets.append((True, 'weird', "I think it's so weird that the kids be calling me Ms.Myia...it makes me feel old!"))
all_tweets.append((True, 'weird', "why are you naked with your socks on that's weird."))